CreateThread(function()
  SFBLIP = AddBlipForCoord(Seller.coords)
  SetBlipSprite (SFBLIP, Seller.SetBlipSprite)
  SetBlipDisplay(SFBLIP, Seller.SetBlipDisplay)
  SetBlipScale  (SFBLIP, Seller.SetBlipScale)
  SetBlipAsShortRange(SFBLIP, true)
  SetBlipColour(SFBLIP, Seller.SetBlipColour)
  BeginTextCommandSetBlipName("STRING")
  AddTextComponentSubstringPlayerName(Seller.BlipLabel)
  EndTextCommandSetBlipName(SFBLIP)
end)
